/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import ojo from './ojo.gltf'

export default function Model(props) {
  const group = useRef()
    const { nodes, materials, animations } = useGLTF(ojo)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        name="Empty"
        position={[1, 5.31, -0.06]}
        rotation={[1.44, 0.2, 1.63]}
        scale={[1, 1, 1]}
      />
      <group position={[0, 0, 0]} rotation={[-1.56, 0.02, -1.56]} scale={[0.91, 0.91, 0.91]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere_2.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere_3.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere_4.geometry}
          material={materials['Material.001']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/ojo_broken_a.gltf')

